---
- name: configure home router server
  hosts: all
  vars_files:
    - files/networking.yml
    - files/key.yml
    - files/torrents.yml
    - files/watchlist.yml
  tasks:
  - name: Install packages
    apt: pkg={{ item }} state=installed
    with_items:
      - mc
    tags: packages

  - include: networking.yml
    tags: network
  - include: security.yml
  - include: transmission.yml
    tags: transmission
  - include: flexget.yml
    tags: flexget
  - include: plex.yml
  - include: samba.yml
    tags: samba
