---
- name: Install Openssh Server
  apt: pkg=openssh-server state=installed update_cache=yes force=yes

- name: Backup sshd_config
  shell: cp /etc/ssh/sshd_config /etc/ssh/sshd_config.bak

- name: Copy sshd config
  template:
    src: templates/sshd_config.j2
    dest: /etc/ssh/sshd_config

- name: Restart ssh service
  service: name=ssh state=restarted

- name: Create .ssh directory
  file:
    path: /root/.ssh
    state: directory
    mode: 0700

- name: Copy public ssh key
  copy:
    content: "{{ public_ssh_key }}"
    dest: /root/.ssh/authorized_keys
